server:
  port: 8082

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

auth:
  validate-url: http://localhost:8081/auth/validate
